{% set name = "loguru-config" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/loguru-config-{{ version }}.tar.gz
  sha256: 432fbc134b118cdfbe0de0226eaab3f5247fc142cd005bf1ebe471f7c572aa34

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - loguru >=0.7.0

test:
  imports:
    - loguru_config
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/erezinman/loguru-config
  summary: Loguru configuration from configuration files.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - erezinman
    - znichollscr
